### ISSUE TITLE
Implement the TypeChecker

### ISSUE THREAD

**Issue by montymxb** [montymxb/FDSSL#2]
type checker needs to be written in

- check for unused opaque types in shaders (outs)
- functions must terminate in a final value
- final values are implicit returns, and cannot be followed by other exprs
- in the case of returns inside of branches, there must be no other expr in any list of exprs outside of that branch
- shaders cannot return singular values, they can only modify state

**Comment by Codysseus** [comment]
Check for unused Opaque Types
