### ISSUE TITLE
Literals within the Block are Return

### ISSUE THREAD

**Issue by Codysseus** [montymxb/FDSSL#7]
A Body is a list of Expressions. Within this body, if there is a literal expression, that becomes an implicit return.
Check within the type checker to enforce the final expression within the body be a literal/variable.

**Comment by montymxb** [comment]
Implicit returns are setup with the pretty printer. Function applications are the exception since they're a bit nebulous to decide when they should return or not.

**Comment by montymxb** [comment]
Closing since we moved to Rust
